services:
  - type: web
    name: rabuddy-backend
    env: python
    buildCommand: "pip install --no-cache-dir flask flask-cors gunicorn"
    startCommand: "python nuclear_app.py"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: ENVIRONMENT  
        value: production
