# FORCE RENDER REFRESH - RAG APP ONLY - July 29, 2025 - 05:51 UTC
services:
  - type: web
    name: rabuddy-backend
    env: python
    buildCommand: "pip install --no-cache-dir -r backend/requirements.txt"
    startCommand: "cd backend && python guaranteed_rag_app.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: ENVIRONMENT  
        value: production
      - key: FORCE_REFRESH
        value: "2025-07-29-05-51"
