services:
  - type: web
    name: rabuddy-backend
    env: python
    buildCommand: "pip install --no-cache-dir -r backend/requirements.txt && echo 'NUCLEAR BUILD COMPLETE'"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT wsgi:app --log-level debug"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: ENVIRONMENT  
        value: production
